# Generated by Django 4.2.11 on 2024-04-18 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SecondApp', '0011_category_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
    ]
